# Generated by Django 3.2.4 on 2021-06-13 01:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_auto_20210613_0719'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='book',
        ),
        migrations.AddField(
            model_name='book',
            name='stock',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.DeleteModel(
            name='Offer',
        ),
        migrations.DeleteModel(
            name='Stock',
        ),
    ]
